### ISSUE TITLE
Build issues on Solaris

### ISSUE THREAD

**Issue by tim-smart** [egorich239/node-compress#2]
Take a look at https://gist.github.com/45be4bcbdea9c32457c0

Not sure what's up here.

**Comment by egorich239** [comment]
Tim,

Could you please tell me your gcc version?

**Comment by tim-smart** [comment]
This was on a Joyent Smartmachine FYI. And considering it is version `3.4.3` that might be the problem.

```
[node@timsmart ~]$ gcc --version
gcc (GCC) 3.4.3 (csl-sol210-3_4-20050802)
Copyright (C) 2004 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by egorich239** [comment]
Is there possibility to update to newer gcc? I suspect the problem is incorrect friends handling by gcc 3.4.3.

**Comment by tim-smart** [comment]
Yeah, upgrading to 4.4 fixed this problem. Closed issue.

**Comment by MaxDesiatov** [comment]
please, add some note about required GCC version to README file

**Comment by egorich239** [comment]
@explicitall: added the note to README.
