### ISSUE TITLE
Fails on OS X 10.6

### ISSUE THREAD

**Issue by nornagon** [egorich239/node-compress#4]
npm install compress, then run demo/demo.js. The result:

$ node /usr/local/lib/node/.npm/compress/0.1.8/package/demo/demo.js
gzip created
Assertion failed: (handle->InternalFieldCount() > 0), function Unwrap, file /usr/local/include/node/node_object_wrap.h, line 29.
[1]    75099 abort      node /usr/local/lib/node/.npm/compress/0.1.8/package/demo/demo.js

**Comment by egorich239** [comment]
Do you use stable node release? Which one?

**Comment by nornagon** [comment]
This is with node from master. I've since rebuilt node v0.2.0 and it works there.

**Comment by gus** [comment]
I am receiving the same error with node v0.3.0. I'll trying going back down to see if it helps.

**Comment by egorich239** [comment]
I have never built node-compress against node v0.3.
