### ISSUE TITLE
node-compress chokes HTTP response on large files

### ISSUE THREAD

**Issue by cskr** [egorich239/node-compress#6]
When I pump a file to node-compress and pump node-compress stream to http.ServerResponse, it freezes the response when the file is large (140MB).  Works fine for small files.  It also works fine with a file writestream.

If I don't use node-compress at all and just pump a fs.readstream to response everything works.

Here is a piece of code which reliably reproduces this.

```
var http = require('http'),
    fs = require('fs'),
    util = require('util'),
    compress = require('compress');

var s = http.createServer(function(req, res) {
    var compressor = new compress.GzipStream();
    res.writeHead(200, {'content-encoding': 'gzip'});

    util.pump(compressor, res);
    util.pump(fs.createReadStream('test.bin'), compressor);
});

s.listen(8080);
```

The test input file can be created with `dd bs=1024 count=143360 if=/dev/zero of=test.bin`.

**Comment by egorich239** [comment]
Fixed in v0.1.10.
