### ISSUE TITLE
Publish v0.1.10 to the npm repo?

### ISSUE THREAD

**Issue by papandreou** [egorich239/node-compress#8]
Hi Ivan,

Thanks for your awesome work. I just realized that a long-standing large file bug (no. 6) was fixed, but in the npm repo it's still Tim-Smart's old v0.1.8 package that's listed as the most recent. Can you update it or should I bug Tim-Smart instead?

Best regards,
Papandreou

**Comment by DTrejo** [comment]
Hello,
I had the same problem when installing from npm.
Cheers!
-David

**Comment by papandreou** [comment]
This is possibly the first issue I ever opened on github :)

Seems unlikely that it will ever happen, or that anyone cares at this point, so I'll close it.
